In [2]:
import pandas as pd
import numpy as np

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
train_df = pd.read_excel('Data_Train.xlsx')

In [5]:
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [6]:
test_df = pd.read_excel('Test_set.xlsx')

In [7]:
test_df.head(1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info

In [8]:
final_df = pd.concat([train_df, test_df])

In [9]:
final_df.head(1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0

In [10]:
final_df.tail(1)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [11]:
# Feature Engineering Process

final_df['Date'] = final_df['Date_of_Journey'].str.split('/').str[0]
final_df['Month'] = final_df['Date_of_Journey'].str.split('/').str[1]
final_df['Year'] =final_df['Date_of_Journey'].str.split('/').str[2]

In [12]:
final_df['Date'] = final_df['Date'].astype(int)
final_df['Month'] = final_df['Month'].astype(int)
final_df['Year'] = final_df['Year'].astype(int)

In [13]:
final_df.drop('Date_of_Journey', axis = 1, inplace = True)

In [14]:
final_df['Arrival_Time'] =  final_df['Arrival_Time'].apply(lambda x: x.split(' ')[0])

In [15]:
final_df['Arrival_hour'] = final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_min'] = final_df['Arrival_Time'].str.split(':').str[1]

In [16]:
final_df['Arrival_hour'] = final_df['Arrival_hour'].astype(int)
final_df['Arrival_min'] = final_df['Arrival_min'].astype(int)

In [17]:
final_df.drop('Arrival_Time', axis = 1, inplace = True)

In [18]:
final_df['Dep_Time'] =  final_df['Dep_Time'].apply(lambda x: x.split(' ')[0])

final_df['Dept_hour'] = final_df['Dep_Time'].str.split(':').str[0]
final_df['Dept_min'] = final_df['Dep_Time'].str.split(':').str[1]

final_df['Dept_hour'] = final_df['Dept_hour'].astype(int)
final_df['Dept_min'] = final_df['Dept_min'].astype(int)

final_df.drop('Dep_Time', axis = 1, inplace = True)

In [19]:
final_df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20

In [20]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [21]:
final_df['Total_Stops'] =  final_df['Total_Stops'].map({'non-stop' : 0, '1 stop': 1,'2 stops':2, '3 stops':3, '4 stops' :4 , np.nan:1 })

In [22]:
final_df['Total_Stops'].unique()

array([0, 2, 1, 3, 4])

In [23]:
final_df.drop('Route', axis = 1, inplace = True)

In [24]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [25]:
final_df['Duration_hour'] =final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [26]:
final_df[final_df['Duration_hour'] == '5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,Duration_hour
6474,Air India,Mumbai,Hyderabad,5m,2,No info,17327.0,6,3,2019,16,55,16,50,5m
2660,Air India,Mumbai,Hyderabad,5m,2,No info,NaN,12,3,2019,16,55,16,50,5m

In [27]:

final_df.drop(6474, axis = 0, inplace = True)

In [28]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13353 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13353 non-null  object
 1   Source           13353 non-null  object
 2   Destination      13353 non-null  object
 3   Duration         13353 non-null  object
 4   Total_Stops      13353 non-null  int64
 5   Additional_Info  13353 non-null  object
 6   Price            10682 non-null  float64
 7   Date             13353 non-null  int64
 8   Month            13353 non-null  int64
 9   Year             13353 non-null  int64
 10  Arrival_hour     13353 non-null  int64
 11  Arrival_min      13353 non-null  int64
 12  Dept_hour        13353 non-null  int64
 13  Dept_min         13353 non-null  int64
 14  Duration_hour    13353 non-null  object
dtypes: float64(1), int64(8), object(6)
memory usage: 1.6+ MB

In [30]:
final_df.drop(2660, axis = 0, inplace = True)

In [31]:
final_df['Duration_hour'] = final_df['Duration_hour'].astype(int)

In [32]:
final_df['Duration_min'] =final_df['Duration'].str.split(' ').str[1].str.split('m').str[0]

In [33]:
final_df['Duration_min'] = final_df['Duration_min'].fillna(0)

In [34]:
final_df['Duration_min'] = final_df['Duration_min'].astype(int)

In [35]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13351 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13351 non-null  object
 1   Source           13351 non-null  object
 2   Destination      13351 non-null  object
 3   Duration         13351 non-null  object
 4   Total_Stops      13351 non-null  int64
 5   Additional_Info  13351 non-null  object
 6   Price            10681 non-null  float64
 7   Date             13351 non-null  int64
 8   Month            13351 non-null  int64
 9   Year             13351 non-null  int64
 10  Arrival_hour     13351 non-null  int64
 11  Arrival_min      13351 non-null  int64
 12  Dept_hour        13351 non-null  int64
 13  Dept_min         13351 non-null  int64
 14  Duration_hour    13351 non-null  int64
 15  Duration_min     13351 non-null  int64
dtypes: float64(1), int64(10), object(5)
memory usage: 1.7+ MB

In [36]:
final_df.drop('Duration', axis = 1, inplace = True)

In [37]:
final_df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [39]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,0,No info,3897.0,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,2,No info,7662.0,1,5,2019,13,15,5,50,7,25
2,Jet Airways,Delhi,Cochin,2,No info,13882.0,9,6,2019,4,25,9,25,19,0
3,IndiGo,Kolkata,Banglore,1,No info,6218.0,12,5,2019,23,30,18,5,5,25
4,IndiGo,Banglore,New Delhi,1,No info,13302.0,1,3,2019,21,35,16,50,4,45

In [38]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()

In [40]:
final_df['Airline'] = labelencoder.fit_transform(final_df['Airline'])
final_df['Source'] = labelencoder.fit_transform(final_df['Source'])
final_df['Destination'] = labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info'] = labelencoder.fit_transform(final_df['Additional_Info'])

In [43]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,Duration_hour,Duration_min
0,3,0,5,0,8,3897.0,24,3,2019,1,10,22,20,2,50
1,1,3,0,2,8,7662.0,1,5,2019,13,15,5,50,7,25
2,4,2,1,2,8,13882.0,9,6,2019,4,25,9,25,19,0
3,3,3,0,1,8,6218.0,12,5,2019,23,30,18,5,5,25
4,3,0,5,1,8,13302.0,1,3,2019,21,35,16,50,4,45

In [45]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder

In [46]:
final_df['Airline'] = ohe.fit_transform(final_df['Airline'])

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'